#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun May 29 19:02:50 2022

@author: sindhucharan
"""

## Import relevant packages
import pandas as pd


##Import data 
path = "/Users/sindhucharan/Downloads/DA Case Material/case_data/Raw data"
Transactions = pd.read_csv(f"{path}/TransactionsData.txt", sep="|", header=0, doublequote=None)
Itemdata=pd.read_csv(f"{path}/ItemData.txt", sep="|", header=0, doublequote=None)
Custdata=pd.read_csv(f"{path}/CustomerData.txt", sep="|", header=0, doublequote=None)

#Check data types in imported data
transactions_type=Transactions.dtypes
print(transactions_type)



#Convert UserID in customer data and Item ID in Item data to string
Custdata['USERID']=Custdata.to_string(columns = ['USERID'])
cust_type=Custdata.dtypes
print(cust_type)

Itemdata['ITEM']=Itemdata.to_string(columns = ['ITEM'])
item_type=Itemdata.dtypes
print(item_type)

## Combinining the three datasets into a single reusable model based on the data dictionary
def Main_data(Tr,Cu,It):
    Main_data=pd.merge(Tr,Cu,on='USERID',how='left')
    Main_data=pd.merge(Main_data,It,on='ITEM',how='left')
    return Main_data
Main_data(Transactions,Custdata,Itemdata)


## Finding inconsistences in the Combined data

Transaction_dup = Transactions[Transactions.duplicated(['USERID'])]
print(Transaction_dup)

